### ISSUE TITLE
Mobile dept

### ISSUE THREAD

**Issue by ashakirzianov** [ashakirzianov/booka-front#142]
- [ ] open links in App
- [ ] implement "scroll to paragraph"
- [ ] implement selection handling
- [ ] drop caps
- [ ] coloring of modal and popover
- [ ] modal title
- [ ] buttons:
    * stretch button
    * palette button
    * tag button
