### ISSUE TITLE
Big refactoring

### ISSUE THREAD

**Issue by ashakirzianov** [ashakirzianov/booka-front#152]

**Comment by ashakirzianov** [comment]
- [ ] Make selection handling internal to RichText
- [ ] Consider flexbox model
- [ ] Pass theme explicitly ?
- [ ] Remove 'Connected' ?
- [ ] Reconsider 'redux-loop' (handle async in components?)
- [ ] 'actionToUrl' should not rely on state
