### ISSUE TITLE
Technical ideas to consider

### ISSUE THREAD

**Issue by ashakirzianov** [ashakirzianov/booka-front#84]
This is an umbrella issue to put various technical ideas we could consider.

- [ ] Use 'FlatList' for mobile rendering
- [ ] Implement 'partially apply' HOC
- [ ] Make <body> black
- [ ] Debug and production versions of 'assertNever'
- [ ] Server-side rendering

**Comment by ashakirzianov** [comment]
- [ ] use 'useReducer' hook

**Comment by ashakirzianov** [comment]
Themability ideas:
- [ ] <Themed render={theme => ... } />
- [ ] get theme from context

**Comment by ashakirzianov** [comment]
- [ ] Adopt RxJS
- [ ] Turn on 'no-lambda-as-props'
